export enum EntityExceptionEnum {
  DELETION_CHECK_EXCEPTION_CONTENT = 'DELETION_CHECK_EXCEPTION_CONTENT',
  RESOURCE_CHECK_EXCEPTION_CONTENT = 'RESOURCE_CHECK_EXCEPTION_CONTENT',
  UNIQUENESS_CHECK_EXCEPTION_CONTENT = 'UNIQUENESS_CHECK_EXCEPTION_CONTENT',
  COMMON_MESSAGE_CONTENT = 'COMMON_MESSAGE_CONTENT',
}
