export enum TreeSelectionTypeEnum {
  SINGLE_PARENT_NODE_SELECTION = 'SINGLE_PARENT_NODE_SELECTION',
  MULTI_PARENT_NODE_SELECTION = 'MULTI_PARENT_NODE_SELECTION',
  STANDARD_MULTI_SELECTION = 'STANDARD_MULTI_SELECTION',
  ONLY_CHILD_SINGLE_SELECTION = 'ONLY_CHILD_SINGLE_SELECTION',
}
