export enum NotificationTemplateTriggerEnum {
  PARTICIPANT_REGISTERED_ON_TRAINING = 'PARTICIPANT_REGISTERED_ON_TRAINING',
  PARTICIPANT_REGISTERED_ON_SYLLABUS = 'PARTICIPANT_REGISTERED_ON_SYLLABUS',
  EVENT_START_REMINDER = 'EVENT_START_REMINDER',
  TIME_OR_PLACE_CHANGED_IN_TRAINING = 'TIME_OR_PLACE_CHANGED_IN_TRAINING',
  TRAINING_CANCELED = 'TRAINING_CANCELED',
  TRAINING_COMPLETED = 'TRAINING_COMPLETED',
  TRAINING_NOT_COMPLETED = 'TRAINING_NOT_COMPLETED',
  CERTIFICATE_NOT_ISSUE = 'CERTIFICATE_NOT_ISSUE',
  CERTIFICATE_ISSUE = 'CERTIFICATE_ISSUE',
  CERTIFICATE_EXPIRES = 'CERTIFICATE_EXPIRES',
}
