export enum GanttEventGroupType {
  ROOM_GROUP = 'ROOM_GROUP',
  MAIN_TRAINER_GROUP = 'MAIN_TRAINER_GROUP',
  LINEAR_TRAINER_GROUP = 'LINEAR_TRAINER_GROUP',
  TRAINER_AS_PARTICIPANT_GROUP = 'TRAINER_AS_PARTICIPANT_GROUP',
  EQUIPMENT_GROUP = 'EQUIPMENT_GROUP',
}
